INSERT INTO PALETTE_A(ID, COLOR) VALUES (1, 'Red');
INSERT INTO PALETTE_A(ID, COLOR) VALUES (2, 'Green');
INSERT INTO PALETTE_A(ID, COLOR) VALUES (3, 'Blue');
INSERT INTO PALETTE_A(ID, COLOR) VALUES (4, 'Purple');
INSERT INTO PALETTE_B(ID, COLOR) VALUES (1, 'Green');
INSERT INTO PALETTE_B(ID, COLOR) VALUES (2, 'Red');
INSERT INTO PALETTE_B(ID, COLOR) VALUES (3, 'Cyan');
INSERT INTO PALETTE_B(ID, COLOR) VALUES (4, 'Brown');