SELECT
  table_name, owner
FROM
  all_tables
ORDER BY
  owner, table_name
  
  -- DUAL = TABELA TEMPORARIA DO ORACLE PARA CONSEGUIR EXECUTAR ALGO
  SELECT SYSDATE FROM DUAL 
  
  65327
-------------------------------------------------------------------------------

SELECT * FROM UF

--ADICIONANDO UMA PRIMARY KEY A UMA TABELA J� CRIADA.
ALTER TABLE UF ADD CONSTRAINT NR_SEQ_UF_PK PRIMARY KEY (NR_SEQUENCIA)


--ADICIONANDO UMA UNIQUE KEY
--FAZENDO COM QUE TENHA UMA CHAVE UNICA ASSIM O ESTADO N�O SE REPETE
ALTER TABLE UF ADD CONSTRAINT SG_UF_UN UNIQUE(SG_UF)
ALTER TABLE UF ADD CONSTRAINT CD_UF_IBGE_UN UNIQUE (CD_UF_IBGE)

--INSERINDO PARAMETROS PARA QUE OS CAMPOS N�O SEJAM NULOS.
ALTER TABLE UF MODIFY (SG_UF NOT NULL,CD_UF_IBGE NOT NULL)

--DROPANDO UMA COSNTRAINT
ALTER TABLE UF DROP CONSTRAINT SG_UF_UN

-------------------------------------------------------------------------------

CREATE TABLE UF(
    NR_SEQUENCIA INTEGER CONSTRAINT NR_SEQ_UF_PK PRIMARY KEY, 
    DT_CRIACAO DATE, 
    DT_ALTERACAO DATE,
    CD_UF_IBGE NUMBER(2) NOT NULL CONSTRAINT CD_UF_IBGE_UN UNIQUE,
    SG_UF VARCHAR2(2) NOT NULL CONSTRAINT SG_UF UNIQUE,
    DS_UF VARCHAR2(255)
    )
    
-------------------------------------------------------------------------------
DROP TABLE MUNICIPIO
SELECT * FROM MUNICIPIO

CREATE TABLE MUNICIPIO(
    NR_SEQUENCIA INTEGER CONSTRAINT NR_SEQ_PK PRIMARY KEY,
    DT_CRIACAO DATE,
    DT_ALTERACAO DATE,
    CD_MUNICIPIO_IBGE NUMBER(7)NOT NULL CONSTRAINT CD_MUNICIPIO_IBGE_UN UNIQUE,
    DS_MUNICIPIO VARCHAR2(255)
)

SELECT * FROM MUNICIPIO
--------------------------------------------------------------------------------

SELECT * FROM PESSOA_FISICA

CREATE TABLE PESSOA_FISICA(
    NR_SEQUENCIA INTEGER CONSTRAINT NR_SEQ_PF_PK PRIMARY KEY,
    DT_CRIACAO DATE, 
    DT_ALTERACAO DATE, 
    NM_PESSOA_FISICA VARCHAR2(255),
    DT_NASCIMENTO DATE, 
    NR_CPF VARCHAR2(11) NOT NULL CONSTRAINT PESSOA_FISICA_CPF_UN UNIQUE,
    QT_ALTURA NUMBER(3,2)
    )
    
--------------------------------------------------------------------------------

SELECT * FROM PESSOA_FISICA_ENDERECO

CREATE TABLE PESSOA_FISICA_ENDERECO(
    NR_SEQUENCIA INTEGER,
    DT_CRIACAO DATE,
    DT_ALTERACAO DATE,
    NR_SEQ_PESSOA_FISICA INTEGER,
    NR_SEQ_UF INTEGER,
    NR_SEQ_MUNICIPIO INTEGER,
    DS_LOGRADOURO VARCHAR2(255),
    NR_ENDERECO INTEGER,
    DS_BAIRRO VARCHAR2(255),
    NR_CEP NUMBER(8)
)

ALTER TABLE PESSOA_FISICA_ENDERECO
    ADD CONSTRAINT NR_SEQ_END_PF_PK
    PRIMARY KEY(NR_SEQUENCIA)
    
--------------------------------------------------------------------------------
--ADICIONANDO FOREIGN KEY A UMA TABELA


ALTER TABLE PESSOA_FISICA_ENDERECO 
    ADD CONSTRAINT 
    NR_SEQ_PF_END_FK FOREIGN KEY(NR_SEQ_PESSOA_FISICA)
    REFERENCES PESSOA_FISICA(NR_SEQUENCIA)
    
-- REFERENCES: INSERINDO PESSOA FISICA ENDERE�O, 
--NR_SEQ_PESSOA_FISICA DEVE EXISTIR NA TABELA PESSOA_FISICA (NR_SEQUENCIA)

ALTER TABLE PESSOA_FISICA_ENDERECO
    ADD CONSTRAINT 
    NR_SEQ_UF_END_FK FOREIGN KEY (NR_SEQ_UF)
    REFERENCES UF(NR_SEQUENCIA)
    

ALTER TABLE PESSOA_FISICA_ENDERECO
    ADD CONSTRAINT 
    NR_SEQ_MUNICIPIO_END_FK FOREIGN KEY (NR_SEQ_MUNICIPIO)
    REFERENCES MUNICIPIO(NR_SEQUENCIA)

--DEFININDO PESSOA FISICA COMO NOT NULL DEVIDO SEMPRE PRECISAR DE UMA PESSOA.

ALTER TABLE PESSOA_FISICA_ENDERECO MODIFY (NR_SEQ_PESSOA_FISICA NOT NULL)


--------------------------------------------------------------------------------
--CONSTRAINT CHECK 


CREATE TABLE TESTE (A1 VARCHAR2(2),B2 NUMBER)
ALTER TABLE TESTE ADD CONSTRAINT A1_CK CHECK (A1 ='X')

--SE A LETRA FOR 'X' ELA � INSERIDA NA TABELA, CASO SEJA DIFERENTE N�O.

ALTER TABLE TESTE ADD CONSTRAINT B2_CK CHECK (B2>= 1)
--SE O NUMERO FOR MAIOR OU IGUAL A 1, � INSERIDO NA TABELA. 


--OUTROS PARAMETROS PARA CONSTRAINT CHECK: 

ALTER TABLE TESTE ADD CONSTRAINT A1_CK CHECK (A1 IN('X','A','B','C'))
--SO SER� POSSIVEL ADICIONAR ESSAS LETRAS

ALTER TABLE TESTE ADD CONSTRAINT B2_CK CHECK (B2 BETWEEN 1 AND 10)
--S� SERA POSSIVEL ADICIONAR VALORES ENTRE 1 E 10.

INSERT INTO TESTE (A1) VALUES('A')
INSERT INTO TESTE (B2) VALUES (10)
SELECT * FROM TESTE